"""Dropped the genre table

Revision ID: 20536fc6a0a4
Revises: 5cc90763b4b3
Create Date: 2025-06-11 17:43:42.431761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20536fc6a0a4'
down_revision = '5cc90763b4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('genre_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('genre',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('genre_id', name=op.f('genre_pkey'))
    )
    # ### end Alembic commands ###
